package enter_types;


import enter_types.bar_type;
import enter_types.event_type;
import enter_types.fitt_type;
import enter_types.garden_type;
import enter_types.meet_type;
import enter_types.pool_type;
import enter_types.resto_type;
import enter_types.wellness_type;
import java.awt.Color;
import java.awt.event.WindowEvent;  // For handling window events like close
import java.awt.Toolkit; 
import javax.swing.*;
import java.awt.*; 
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

public class amenity_info extends javax.swing.JFrame {

    /**
     * Creates new form amenity_info
     */
    public amenity_info() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pool_btn = new javax.swing.JButton();
        bar_btn = new javax.swing.JButton();
        meet_btn = new javax.swing.JButton();
        wellnesss_btn = new javax.swing.JButton();
        garden_btn = new javax.swing.JButton();
        resto_btn = new javax.swing.JButton();
        event_btn = new javax.swing.JButton();
        fitt_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("AMENITIES");
        jLabel4.setToolTipText("");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 10, 190, 60));

        pool_btn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        pool_btn.setText("SWIMMING POOL");
        pool_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pool_btnActionPerformed(evt);
            }
        });
        jPanel1.add(pool_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 140, 390, 50));

        bar_btn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bar_btn.setText("BARS");
        bar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bar_btnActionPerformed(evt);
            }
        });
        jPanel1.add(bar_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 260, 390, 50));

        meet_btn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        meet_btn.setText("MEETING SPACES");
        meet_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meet_btnActionPerformed(evt);
            }
        });
        jPanel1.add(meet_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 320, 390, 50));

        wellnesss_btn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        wellnesss_btn.setText("SPA AND WELLNES CENTER");
        wellnesss_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wellnesss_btnActionPerformed(evt);
            }
        });
        jPanel1.add(wellnesss_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 380, 390, 50));

        garden_btn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        garden_btn.setText("OUTDOOR LOUNGE AREA");
        garden_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                garden_btnActionPerformed(evt);
            }
        });
        jPanel1.add(garden_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 500, 390, 60));

        resto_btn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        resto_btn.setText("RESTAURANT");
        resto_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resto_btnActionPerformed(evt);
            }
        });
        jPanel1.add(resto_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 200, 390, 50));

        event_btn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        event_btn.setText("EVENT SPACES");
        event_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                event_btnActionPerformed(evt);
            }
        });
        jPanel1.add(event_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 440, 390, 50));

        fitt_btn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        fitt_btn.setText("FITNESS AREA");
        fitt_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fitt_btnActionPerformed(evt);
            }
        });
        jPanel1.add(fitt_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 570, 390, 60));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picf.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 770));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 1660, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 780));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fitt_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fitt_btnActionPerformed
        // TODO add your handling code here:
        fitt_type ft = new fitt_type();
        ft.setVisible(true);
    }//GEN-LAST:event_fitt_btnActionPerformed

    private void event_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_event_btnActionPerformed
        // TODO add your handling code here:
        event_type et = new event_type();
        et.setVisible(true);

    }//GEN-LAST:event_event_btnActionPerformed

    private void resto_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resto_btnActionPerformed
        // TODO add your handling code here:
        resto_type rt = new resto_type();
        rt.setVisible(true);
    }//GEN-LAST:event_resto_btnActionPerformed

    private void garden_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_garden_btnActionPerformed
        // TODO add your handling code here:
        garden_type gt = new garden_type();
        gt.setVisible(true);
    }//GEN-LAST:event_garden_btnActionPerformed

    private void wellnesss_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wellnesss_btnActionPerformed
        // TODO add your handling code here:
        wellness_type wt = new wellness_type();
        wt.setVisible(true);
    }//GEN-LAST:event_wellnesss_btnActionPerformed

    private void meet_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meet_btnActionPerformed
        // TODO add your handling code here:
        meet_type mt = new meet_type();
        mt.setVisible(true);
    }//GEN-LAST:event_meet_btnActionPerformed

    private void bar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bar_btnActionPerformed
        // TODO add your handling code here:
        bar_type bt = new bar_type();
        bt.setVisible(true);
    }//GEN-LAST:event_bar_btnActionPerformed

    private void pool_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pool_btnActionPerformed
        // TODO add your handling code here:
        pool_type pt = new pool_type();
        pt.setVisible(true);
    }//GEN-LAST:event_pool_btnActionPerformed
    public void close(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
                }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(amenity_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(amenity_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(amenity_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(amenity_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new amenity_info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bar_btn;
    private javax.swing.JButton event_btn;
    private javax.swing.JButton fitt_btn;
    private javax.swing.JButton garden_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton meet_btn;
    private javax.swing.JButton pool_btn;
    private javax.swing.JButton resto_btn;
    private javax.swing.JButton wellnesss_btn;
    // End of variables declaration//GEN-END:variables
}
