/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package inquiry_info;

import offerings_reservation.list_offering;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import solace.DashboardOP;



public class reservation_information extends javax.swing.JFrame {

    /**
     * Creates new form reservation_information
     */
    public reservation_information() {
        initComponents();
        loadData(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btnENTER = new javax.swing.JButton();
        emailc = new javax.swing.JTextField();
        agec = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        genderc = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        clients_table = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        namec = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        go_toReserve = new javax.swing.JButton();
        cbCID = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SELECT AN ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 420, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 320, -1, -1));

        btnENTER.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnENTER.setText("ENTER");
        btnENTER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnENTERActionPerformed(evt);
            }
        });
        getContentPane().add(btnENTER, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 320, -1, -1));

        emailc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        emailc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailcActionPerformed(evt);
            }
        });
        getContentPane().add(emailc, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 190, 400, 30));

        agec.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        agec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agecActionPerformed(evt);
            }
        });
        getContentPane().add(agec, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 230, 400, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("EMAIL");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 190, -1, 20));

        genderc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        genderc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gendercActionPerformed(evt);
            }
        });
        getContentPane().add(genderc, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 270, 400, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("GENDER");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 280, -1, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("AGE");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 240, -1, 20));

        clients_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Inquirer Name", "Email", "Age", "Gender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        clients_table.setName(""); // NOI18N
        jScrollPane1.setViewportView(clients_table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 740, 650));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("INQUIRY");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INQUIRER INFORMATION");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 110, -1, -1));

        namec.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        namec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namecActionPerformed(evt);
            }
        });
        getContentPane().add(namec, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 150, 400, 30));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NAME");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 150, -1, 20));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("NAME");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 150, -1, 20));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("INQUIRER INFORMATION");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 110, -1, -1));

        go_toReserve.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        go_toReserve.setText("GO TO RESERVATION");
        go_toReserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                go_toReserveActionPerformed(evt);
            }
        });
        getContentPane().add(go_toReserve, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 490, 180, 30));

        cbCID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbCID, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 450, 450, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inquiry_info/logo-removebg-preview__1_-removebg-preview.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 550, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inquiry_info/bg.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnENTERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnENTERActionPerformed
                                     
    // Get text from the fields
    

    // Check if required fields are empty

        String Name = namec.getText().trim();
        String Email = emailc.getText().trim();
        String Age = agec.getText().trim();
        String Gender = genderc.getText().trim();

        // Check if required fields are empty
        if (Name.isEmpty() || Email.isEmpty() || Age.isEmpty() || Gender.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields are required!");
            return; // Exit the method if any field is empty
        }

        // Establish connection
        Connection con = null;
        PreparedStatement ps = null;
        ResultSet rs = null;

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/databaseresort", "root", "");

            // Insert new client information into the database
            ps = con.prepareStatement("INSERT INTO clients(client_name, email, age, gender) VALUES (?, ?, ?, ?)", Statement.RETURN_GENERATED_KEYS);
            ps.setString(1, Name);
            ps.setString(2, Email);
            ps.setString(3, Age); 
            ps.setString(4, Gender);
            ps.executeUpdate();

            // Fetch the generated keys (client_id)
            rs = ps.getGeneratedKeys();
            if (rs.next()) {
                int generatedId = rs.getInt(1); // Get the generated ID
                cbCID.addItem(String.valueOf(generatedId)); // Add the new ID to the combo box
            }

            // Optionally show a success message
            JOptionPane.showMessageDialog(this, "Reservation made successfully!");

            // Clear the input fields after successful reservation
            namec.setText("");
            emailc.setText("");
            agec.setText("");
            genderc.setText("");

            // Update the table with the latest data from the database
            updateTableData();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "An error occurred while saving data: " + ex.getMessage());
            Logger.getLogger(reservation_information.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            // Close resources
            try {
                if (rs != null) rs.close();
                if (ps != null) ps.close();
                if (con != null) con.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnENTERActionPerformed
    private void updateTableData() {
    // Clear the existing rows
    DefaultTableModel model = (DefaultTableModel) clients_table.getModel();
    model.setRowCount(0);  // Remove all rows from the table
    
    // Fetch the data from the database and add it to the table
    Connection con = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    try {
        // Establish connection
        con = DriverManager.getConnection("jdbc:mysql://localhost/databaseresort", "root", "");
        
        // Fetch the data from the 'clients' table
        ps = con.prepareStatement("SELECT client_id, client_name, email, age, gender FROM clients");
        rs = ps.executeQuery();
        
        // Populate the table with the fetched data
        while (rs.next()) {
            String id = rs.getString("client_id");
            String name = rs.getString("client_name");
            String email = rs.getString("email");
            String age = rs.getString("age");
            String gender = rs.getString("gender");
            
            // Add a new row to the table
            model.addRow(new Object[] {id, name, email, age, gender});
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "An error occurred while fetching data: " + ex.getMessage());
        Logger.getLogger(reservation_information.class.getName()).log(Level.SEVERE, null, ex);
    } finally {
        try {
            if (rs != null) rs.close();
            if (ps != null) ps.close();
            if (con != null) con.close();
        } catch (SQLException ex) {
            Logger.getLogger(reservation_information.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}

    
    private void loadData() {
        Connection con = null;
        Statement stmt = null;
        ResultSet rs = null;
        DefaultTableModel model = (DefaultTableModel) clients_table.getModel();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/databaseresort", "root", "");
            stmt = con.createStatement();
            String query = "SELECT client_id, client_name, email, age, gender FROM clients";
            rs = stmt.executeQuery(query);

            model.setRowCount(0);
            cbCID.removeAllItems(); // Clear previous items

            while (rs.next()) {
                String id = rs.getString("client_id");
                String name = rs.getString("client_name");
                String email = rs.getString("email");
                String age = rs.getString("age");
                String gender = rs.getString("gender");

                model.addRow(new Object[] { id, name, email, age, gender });
                cbCID.addItem(id); // Add client_id to the combo box
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "An error occurred while fetching data: " + ex.getMessage());
            Logger.getLogger(reservation_information.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                if (rs != null) rs.close();
                if (stmt != null) stmt.close();
                if (con != null) con.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }

    private void emailcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailcActionPerformed

    private void agecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agecActionPerformed

    private void gendercActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gendercActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gendercActionPerformed

    private void namecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namecActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DashboardOP Dsh = new DashboardOP();
        Dsh.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void go_toReserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_go_toReserveActionPerformed
        String selectedId = (String) cbCID.getSelectedItem();
        String clientName = ""; // Variable to hold the client's name

        if (selectedId != null) {
            // Fetch the client's name from the database based on the selected client_id
            Connection con = null;
            PreparedStatement ps = null;
            ResultSet rs = null;

            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost/databaseresort", "root", "");
                String query = "SELECT client_name FROM clients WHERE client_id = ?";
                ps = con.prepareStatement(query);
                ps.setString(1, selectedId);
                rs = ps.executeQuery();

                if (rs.next()) {
                    clientName = rs.getString("client_name");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "An error occurred while fetching the client's name: " + ex.getMessage());
                Logger.getLogger(reservation_information.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    if (rs != null) rs.close();
                    if (ps != null) ps.close();
                    if (con != null) con.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }

        // Create and show the list_offering frame, passing the client's name
        list_offering lo = new list_offering();
        lo.setName(clientName); // Set the client's name in the list_offering frame
        lo.setVisible(true);
    }//GEN-LAST:event_go_toReserveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reservation_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reservation_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reservation_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reservation_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reservation_information().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField agec;
    private javax.swing.JButton btnENTER;
    private javax.swing.JComboBox<String> cbCID;
    private javax.swing.JTable clients_table;
    private javax.swing.JTextField emailc;
    private javax.swing.JTextField genderc;
    private javax.swing.JButton go_toReserve;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField namec;
    // End of variables declaration//GEN-END:variables
}
