package payment;

import inquiry_info.reservation_information;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;




/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author elhaizamae
 */
public class transactions extends javax.swing.JFrame {

    /**
     * Creates new form transactions
     */
    public transactions() {
        initComponents();
        loadData();
    }
    
    private Connection connectToDatabase(){
        String url = "jdbc:mysql://localhost:3306/databaseresort";
        String user = "root";
        String password = "";
        Connection con = null;
        
        try {
            con = DriverManager.getConnection(url,user,password);
        } catch(SQLException e){
            e.printStackTrace();
        }
        return con;
    }
private void loadData() {
    Connection con = null;
    Statement stmt = null;
    ResultSet rs = null;
    DefaultTableModel model = (DefaultTableModel) trans_table.getModel();

    try {
        // Establish connection
        con = connectToDatabase();
        if (con == null) {
            JOptionPane.showMessageDialog(this, "Failed to connect to the database.");
            return; // Exit the method if connection is null
        }
        stmt = con.createStatement();
        
        // Query to select all rows from the transaction_history table
        String query = "SELECT transaction_id, client_name, email, age, gender, price, offers, datetime, types FROM transaction_history";
        rs = stmt.executeQuery(query);

        // Clear existing rows in the table
        model.setRowCount(0);

        // Add rows from ResultSet to the table
        while (rs.next()) {
            String id = rs.getString("transaction_id");                
            String name = rs.getString("client_name");
            String email = rs.getString("email");
            String age = rs.getString("age");
            String gender = rs.getString("gender");
            String types = rs.getString("types");
            String offers = rs.getString("offers");
            String datetime = rs.getString("datetime");
            String price = rs.getString("price");

            model.addRow(new Object[] {id, name, email, age, gender, types, offers, datetime, price });
        }

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "An error occurred while fetching data: " + ex.getMessage());
        Logger.getLogger(transactions.class.getName()).log(Level.SEVERE, null, ex);
    } finally {
        try {
            if (rs != null) rs.close();
            if (stmt != null) stmt.close();
            if (con != null) con.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        trans_table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        trans_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Transaction ID", "Name", "Email", "Age", "Gender", "Date/Time", "Types", "Offers", "Price"
            }
        ));
        jScrollPane1.setViewportView(trans_table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 1290, 520));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PAYMENT TRANSACTION");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, -1));

        jLabel2.setBackground(new java.awt.Color(102, 51, 0));
        jLabel2.setForeground(new java.awt.Color(102, 51, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inquiry_info/bg.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, -10, 1580, 830));

        jLabel3.setBackground(new java.awt.Color(102, 51, 0));
        jLabel3.setForeground(new java.awt.Color(102, 51, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inquiry_info/bg.png"))); // NOI18N
        jLabel3.setText("jLabel2");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-600, -30, 1580, 830));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transactions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable trans_table;
    // End of variables declaration//GEN-END:variables
}
