
import java.awt.Color;
import java.awt.event.WindowEvent;  // For handling window events like close
import java.awt.Toolkit; 
import javax.swing.*;
import java.awt.*; 
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

public class amenity_info extends javax.swing.JFrame {

    /**
     * Creates new form amenity_info
     */
    public amenity_info() {
        initComponents();
         bar_btn.setBackground(new Color(0, 0, 0, 0));
         fitt_btn.setBackground(new Color(0, 0, 0, 0));
         pool_btn.setBackground(new Color(0, 0, 0, 0));
         meet_btn.setBackground(new Color(0, 0, 0, 0));
         resto_btn.setBackground(new Color(0, 0, 0, 0));
         wellnesss_btn.setBackground(new Color(0, 0, 0, 0));
         garden_btn.setBackground(new Color(0, 0, 0, 0));
         event_btn.setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pool_btn = new javax.swing.JButton();
        resto_btn = new javax.swing.JButton();
        garden_btn = new javax.swing.JButton();
        wellnesss_btn = new javax.swing.JButton();
        bar_btn = new javax.swing.JButton();
        meet_btn = new javax.swing.JButton();
        event_btn = new javax.swing.JButton();
        fitt_btn = new javax.swing.JButton();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        label10 = new java.awt.Label();
        label11 = new java.awt.Label();
        label12 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 768));

        pool_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swimming-pool.png"))); // NOI18N
        pool_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pool_btnActionPerformed(evt);
            }
        });

        resto_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant.png"))); // NOI18N
        resto_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resto_btnActionPerformed(evt);
            }
        });

        garden_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/park.png"))); // NOI18N
        garden_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                garden_btnActionPerformed(evt);
            }
        });

        wellnesss_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spa.png"))); // NOI18N
        wellnesss_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wellnesss_btnActionPerformed(evt);
            }
        });

        bar_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cocktail.png"))); // NOI18N
        bar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bar_btnActionPerformed(evt);
            }
        });

        meet_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/round-table.png"))); // NOI18N
        meet_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meet_btnActionPerformed(evt);
            }
        });

        event_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barrier.png"))); // NOI18N
        event_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                event_btnActionPerformed(evt);
            }
        });

        fitt_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\elhaizamae\\Desktop\\MINEE\\2ND YEAR\\resort_features\\amn_button\\gym.png")); // NOI18N
        fitt_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fitt_btnActionPerformed(evt);
            }
        });

        label5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        label5.setName(""); // NOI18N
        label5.setText("Spa and Wellness Center");

        label6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        label6.setText("Outdoor Lounge Area");

        label7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        label7.setText("Bars");

        label8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        label8.setName(""); // NOI18N
        label8.setText("Meeting Rooms");

        label9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        label9.setText("Swimming Pools");

        label10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        label10.setText("Conference and Event Spaces");

        label11.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        label11.setText("Restaurants");

        label12.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        label12.setText("Fitness Center");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bar_btn)
                            .addComponent(pool_btn)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(meet_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wellnesss_btn, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fitt_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resto_btn)
                            .addComponent(event_btn)
                            .addComponent(garden_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pool_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(garden_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(bar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(resto_btn, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(32, 32, 32))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(meet_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(wellnesss_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(event_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fitt_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void close(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
                }
    
    private void fitt_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fitt_btnActionPerformed
        // TODO add your handling code here:
        fitt_type ft = new fitt_type();
        ft.setVisible(true);
    }//GEN-LAST:event_fitt_btnActionPerformed

    private void garden_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_garden_btnActionPerformed
        // TODO add your handling code here:
        garden_type gt = new garden_type();
        gt.setVisible(true);
    }//GEN-LAST:event_garden_btnActionPerformed

    private void resto_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resto_btnActionPerformed
        // TODO add your handling code here:
        resto_type rt = new resto_type();
        rt.setVisible(true);
    }//GEN-LAST:event_resto_btnActionPerformed

    private void pool_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pool_btnActionPerformed
        // TODO add your handling code here:
        pool_type pt = new pool_type();
        pt.setVisible(true);
    }//GEN-LAST:event_pool_btnActionPerformed

    private void meet_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meet_btnActionPerformed
        // TODO add your handling code here:
        meet_type mt = new meet_type();
        mt.setVisible(true);
    }//GEN-LAST:event_meet_btnActionPerformed

    private void wellnesss_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wellnesss_btnActionPerformed
        // TODO add your handling code here:
        wellness_type wt = new wellness_type();
        wt.setVisible(true);
    }//GEN-LAST:event_wellnesss_btnActionPerformed

    private void event_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_event_btnActionPerformed
        // TODO add your handling code here:
        event_type et = new event_type();
        et.setVisible(true);
     
    }//GEN-LAST:event_event_btnActionPerformed

    private void bar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bar_btnActionPerformed
        // TODO add your handling code here:
        bar_type bt = new bar_type();
        bt.setVisible(true);
    }//GEN-LAST:event_bar_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(amenity_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(amenity_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(amenity_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(amenity_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new amenity_info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bar_btn;
    private javax.swing.JButton event_btn;
    private javax.swing.JButton fitt_btn;
    private javax.swing.JButton garden_btn;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private javax.swing.JButton meet_btn;
    private javax.swing.JButton pool_btn;
    private javax.swing.JButton resto_btn;
    private javax.swing.JButton wellnesss_btn;
    // End of variables declaration//GEN-END:variables
}
