/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package solace;

/**
 *
 * @author Huawei Matebook
 */
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.*;    // For JFrame, JTextField, JPasswordField, JButton, JOptionPane
import java.awt.event.*;  // For ActionListener and ActionEvent

public class Login extends javax.swing.JFrame {

    public class UserData {
    public static String email;      // Store the email entered during SignUp
    public static String password;   // Store the password entered during SignUp
}
    
private String enteredEmail;
    private String enteredPassword;
    // Declare components for the login form (email and password fields)
    private JTextField emailLogInField;
    private JPasswordField passLogInField;
    
    public Login() {
        initComponents();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        emailLogIn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passLogIn = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        signUp = new javax.swing.JButton();
        LogIn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("MS UI Gothic", 0, 48)); // NOI18N
        jLabel1.setText("Log in to your Account");

        jLabel2.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        jLabel2.setText("Email:");

        emailLogIn.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        emailLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailLogInActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        jLabel3.setText("Password:");

        passLogIn.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        passLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passLogInActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jLabel4.setText("Don't have an account?");

        signUp.setBackground(new java.awt.Color(0, 102, 255));
        signUp.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        signUp.setForeground(new java.awt.Color(255, 255, 255));
        signUp.setText("Sign Up!");
        signUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpActionPerformed(evt);
            }
        });

        LogIn.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        LogIn.setText("Log In");
        LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(emailLogIn, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(passLogIn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(signUp))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(359, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel1)
                .addGap(69, 69, 69)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emailLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(passLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(signUp))
                .addGap(94, 94, 94)
                .addComponent(LogIn)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void signUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpActionPerformed
        SignUp sinup = new SignUp();  // Create a new instance of the SignUp frame
        sinup.setVisible(true);  // Make the SignUp frame visible
        
        this.dispose();
    }//GEN-LAST:event_signUpActionPerformed

    private void emailLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailLogInActionPerformed
//this should be matching to the email inputed to the register one
    String enteredEmail = emailLogInField.getText();  // Assuming emailLogInField is the login email text field

    }//GEN-LAST:event_emailLogInActionPerformed

    private void passLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passLogInActionPerformed
//this should be matching to the password inputed to the register one
    String enteredPassword = new String(passLogInField.getPassword());  // Assuming passLogInField is the password field
     }//GEN-LAST:event_passLogInActionPerformed

    private void LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInActionPerformed
//this will only work if the data inserted is matching to the sign up one    
if (emailLogInField.getText().equals(UserData.email) && new String(passLogInField.getPassword()).equals(UserData.password)) {
        JOptionPane.showMessageDialog(this, "Login successful!", "Success", JOptionPane.INFORMATION_MESSAGE);
        // Proceed to the next window or main screen
    } else {
        JOptionPane.showMessageDialog(this, "Invalid email or password.", "Error", JOptionPane.ERROR_MESSAGE);
    }
     }//GEN-LAST:event_LogInActionPerformed

    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
    try {
        // Set the Look and Feel to Nimbus if it's available
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;  // If Nimbus is available, use it
            }
        }
    } catch (Exception ex) {
        // Log any exceptions related to setting the Look and Feel
        java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

    // Use EventQueue to safely create and display the Login frame
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new Login().setVisible(true); // Make sure Login has a no-argument constructor
        }
    });
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogIn;
    private javax.swing.JTextField emailLogIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField passLogIn;
    private javax.swing.JButton signUp;
    // End of variables declaration//GEN-END:variables
}
