/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package solace;

/**
 *
 * @author Huawei Matebook
 */
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.event.*;

public class Login extends javax.swing.JFrame {
private String defaultEmail = "admin@gmail.com";
private String defaultPassword = "12345678";

    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        emailLogIn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passLogIn = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        signUp = new javax.swing.JButton();
        LogIn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("MS UI Gothic", 0, 68)); // NOI18N
        jLabel1.setText("LOGIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("MS UI Gothic", 0, 48)); // NOI18N
        jLabel2.setText("Email:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, -1, -1));

        emailLogIn.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        emailLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailLogInActionPerformed(evt);
            }
        });
        getContentPane().add(emailLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 397, -1));

        jLabel3.setFont(new java.awt.Font("MS UI Gothic", 0, 48)); // NOI18N
        jLabel3.setText("Password:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, -1, -1));

        passLogIn.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        passLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passLogInActionPerformed(evt);
            }
        });
        getContentPane().add(passLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 490, 397, 49));

        jLabel4.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        jLabel4.setText("Forgot password?");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 560, -1, -1));

        signUp.setBackground(new java.awt.Color(0, 102, 255));
        signUp.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        signUp.setForeground(new java.awt.Color(255, 255, 255));
        signUp.setText("Reset");
        signUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpActionPerformed(evt);
            }
        });
        getContentPane().add(signUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 550, -1, -1));

        LogIn.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        LogIn.setText("Log In");
        LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInActionPerformed(evt);
            }
        });
        getContentPane().add(LogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 680, 225, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Huawei Matebook\\Downloads\\462574788-27900747346205854-1976.png")); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1470, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void signUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpActionPerformed
String newPassword = JOptionPane.showInputDialog(this, "Enter your new password:", "Forgot Password", JOptionPane.PLAIN_MESSAGE);

    if (newPassword != null && !newPassword.trim().isEmpty()) {
        if (newPassword.length() >= 8) {
            defaultPassword = newPassword;
            JOptionPane.showMessageDialog(this, "Password updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Password must be at least 8 characters long.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Password update canceled.", "Info", JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_signUpActionPerformed

    private void emailLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailLogInActionPerformed

    }//GEN-LAST:event_emailLogInActionPerformed

    private void passLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passLogInActionPerformed

     }//GEN-LAST:event_passLogInActionPerformed

    private void LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInActionPerformed
  String enteredEmail = emailLogIn.getText(); // Assuming emailLogIn is a JTextField
    String enteredPassword = passLogIn.getText(); // Assuming passLogIn is a JPasswordField

    if (enteredEmail.equals(defaultEmail) && enteredPassword.equals(defaultPassword)) {
        JOptionPane.showMessageDialog(this, "Login Successful!", "Success", JOptionPane.INFORMATION_MESSAGE);

        DashboardOP DOP = new DashboardOP();
        DOP.setVisible(true);
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Invalid Email or Password!", "Error", JOptionPane.ERROR_MESSAGE);
    }

     }//GEN-LAST:event_LogInActionPerformed

    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception ex) {
        java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new Login().setVisible(true);
        }
    });
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogIn;
    private javax.swing.JTextField emailLogIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField passLogIn;
    private javax.swing.JButton signUp;
    // End of variables declaration//GEN-END:variables
}
